Terminal close -- exit!
pubs;

CREATE DATABASE IF NOT EXISTS pubs;
USE pubs;

CREATE TABLE IF NOT EXISTS EMPLEADO(
    DNI_EMPLEADO VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DOMICILIO VARCHAR(100),
    PRIMARY KEY (DNI_EMPLEADO)
);

CREATE TABLE IF NOT EXISTS PUB(
    COD_PUB VARCHAR(100) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    LICENCIA_FISCAL VARCHAR(100) NOT NULL,
    DOMICILIO VARCHAR(100),
    FECHA_APERTURA DATE NOT NULL,
    HORARIO ENUM('HOR1', 'HOR2', 'HOR3') NOT NULL,
    COD_LOCALIDAD INT NOT NULL,
    PRIMARY KEY (COD_PUB)
);

CREATE TABLE IF NOT EXISTS PUB_EMPLEADO(
    COD_PUB VARCHAR(100) NOT NULL,
    DNI_EMPLEADO VARCHAR(100) NOT NULL, 
    FUNCION ENUM('CAMARERO', 'SEGURIDAD', 'LIMPIEZA'),
    PRIMARY KEY (COD_PUB, DNI_EMPLEADO)
);

CREATE TABLE IF NOT EXISTS EXISTENCIAS(
    COD_ARTICULO VARCHAR(100) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO INT NOT NULL,
    COD_PUB VARCHAR(100) NOT NULL,
    PRIMARY KEY (COD_ARTICULO),
    FOREIGN KEY (COD_PUB) REFERENCES PUB (COD_PUB)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS TITULAR(
    DNI_TITULAR VARCHAR(100) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DOMICILIO VARCHAR(100),
    COD_PUB VARCHAR(100) NOT NULL,
    PRIMARY KEY (DNI_TITULAR),
    FOREIGN KEY (COD_PUB) REFERENCES PUB (COD_PUB)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS LOCALIDAD(
    COD_LOCALIDAD VARCHAR(100) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    PRIMARY KEY (COD_LOCALIDAD)
);